export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_ITEM_QUANTITY = "UPDATE_CART_ITEM_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
export const SET_CHECK_STATUS = "SET_CHECK_STATUS";
export const UPDATE_PAYMENT_INFO = 'UPDATE_PAYMENT_INFO';
export const ADD_TO_ADDRESSES = 'ADD_TO_ADDRESSES';